name: icecreamshop-stack

services:
  main-db:
    image: postgres:16-alpine
    container_name: main-db
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - icecreamshop_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icecreamshopadmin -d icecreamshop-db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - icecreamshop-network

volumes:
  icecreamshop_data:

networks:
  icecreamshop-network:
    external: true