services:
  icecreamshop-dotnet-api:
    build: .
    container_name: icecreamshop-dotnet-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IceCreamShopDbConn=Host=icecreamshop-postgresql-db;Port=5432;Database=icecreamshop-db;Username=icecreamshopadmin;Password=icecreamshop123
    networks:
      - icecreamshop-network

networks:
  icecreamshop-network:
    external: true